### ISSUE TITLE
Error with v4 running with weewx v4 beta and python 3

### ISSUE THREAD

**Issue by bellrichm** [gjr80/weewx-realtime_gauge-data#18]
I got this error:

Nov 19 16:41:46 pi weewx[8218] INFO user.rtgd: rtgdthread: **** Traceback (most recent call last):
Nov 19 16:41:46 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1242, in process_packet
Nov 19 16:41:46 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     data = self.calculate(cached_packet)
Nov 19 16:41:46 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1845, in calculate
Nov 19 16:41:46 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     wgust_tm = max(wgust_m_loop, wgust_tm, 0.0)
Nov 19 16:41:46 pi weewx[8218] INFO user.rtgd: rtgdthread: **** TypeError: unorderable types: float() > NoneType()
Nov 19 16:41:48 pi weewx[8218] INFO user.rtgd: rtgdthread: **** Traceback (most recent call last):
Nov 19 16:41:48 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1242, in process_packet
Nov 19 16:41:48 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     data = self.calculate(cached_packet)
Nov 19 16:41:48 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1845, in calculate
Nov 19 16:41:48 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     wgust_tm = max(wgust_m_loop, wgust_tm, 0.0)
Nov 19 16:41:48 pi weewx[8218] INFO user.rtgd: rtgdthread: **** TypeError: unorderable types: float() > NoneType()
Nov 19 16:41:50 pi weewx[8218] INFO user.rtgd: rtgdthread: **** Traceback (most recent call last):
Nov 19 16:41:50 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1242, in process_packet
Nov 19 16:41:50 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     data = self.calculate(cached_packet)
Nov 19 16:41:50 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1845, in calculate
Nov 19 16:41:50 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     wgust_tm = max(wgust_m_loop, wgust_tm, 0.0)
Nov 19 16:41:50 pi weewx[8218] INFO user.rtgd: rtgdthread: **** TypeError: unorderable types: float() > NoneType()
Nov 19 16:41:52 pi weewx[8218] INFO user.rtgd: rtgdthread: **** Traceback (most recent call last):
Nov 19 16:41:52 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1242, in process_packet
Nov 19 16:41:52 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     data = self.calculate(cached_packet)
Nov 19 16:41:52 pi weewx[8218] INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1845, in calculate
Nov 19 16:41:52 pi weewx[8218] INFO user.rtgd: rtgdthread: ****     wgust_tm = max(wgust_m_loop, wgust_tm, 0.0)
Nov 19 16:41:52 pi weewx[8218] INFO user.rtgd: rtgdthread: **** TypeError: unorderable types: float() > NoneType()

Note, weeutil has a max_with_none function.
- rich

**Comment by gjr80** [comment]
Thanks, wasn't aware of the change. Fixed under 0.4.1.

**Comment by bellrichm** [comment]
Thanks. Got past that error, but now got this error. If you want me to just try a patch, I am open to that.

INFO user.rtgd: rtgdthread: **** TypeError: unorderable types: NoneType() <= float()
INFO user.rtgd: rtgdthread: **** Traceback (most recent call last):
INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1246, in process_packet
INFO user.rtgd: rtgdthread: ****     data = self.calculate(cached_packet)
INFO user.rtgd: rtgdthread: ****   File "/home/pi/4.0.0b1/bin/user/rtgd.py", line 1864, in calculate
INFO user.rtgd: rtgdthread: ****     twgust_tm = time.localtime(self.day_stats['wind'].maxtime) if wgust_m_loop <= wgust_tm else \

**Comment by gjr80** [comment]
Try the current master version of `rtgd.py`.

```
$ wget https://raw.githubusercontent.com/gjr80/weewx-realtime_gauge-data/master/bin/user/rtgd.py
```
should pull it down.

**Comment by bellrichm** [comment]
Drat, didn’t think this totally through. Current weather conditions aren’t triggering the error. I have a couple of Ideas. (1) Hack the simulator driver to emit the data. (2) Write a driver that reads my DB and emits loop packets/archive records for each DB record.
I’m going for (2). Seems like a good way to do some regression against real data.  Plus, it should be pretty easy.
Not sure  how soon I will get to it.  Feel free to close this issue.  I can reopen if necessary.
Thanks for all your work. 
-rich

**Comment by gjr80** [comment]
So what conditions are causing the issue? windSpeed = None in a loop packet? Changing the simulator driver to emit one or more fields with the value None is very easily done, just a couple of lines of code. Sure you could emit archive records from archive as loop packets but you will not likely see the same conditions that lead to the issue. If you emit archive records from archive as archive records where does the loop data come from.

When I issued 0.4.1 I did some check with the simulator emitting None values but clearly did not hit the problem condition.

Out of interest what type of station/driver is being used?

**Comment by bellrichm** [comment]
Unfortunately I am not sure, but I think it is windSpeed = None. Luckily it is calm again and I can confirm the fix. Also agree that I might not have the data in my historical data.

The station is a VP2. But I have a modified setup where I gather the data on one Pi and run the reports and rtgd service on a separate one - not that in this case it should matter....

Thanks for the fix. - rich
