### ISSUE TITLE
Exception: wgust AttributeError NoneType

### ISSUE THREAD

**Issue by LMSSonos** [gjr80/weewx-realtime_gauge-data#25]
Hi, 

I did the manual installation as described but I always get following error. I didn't manage to find out what the issue is, sounds like some config is missing but I didn't find anything about the windGust.

Thanks for your help

```
weewx    | Aug 26 21:02:07 weewx[19] INFO user.rtgd: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 1815, in process_packet
weewx    | Aug 26 21:02:07 weewx[19] INFO user.rtgd: rtgdthread: ****     data = self.calculate(cached_packet)
weewx    | Aug 26 21:02:07 weewx[19] INFO user.rtgd: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 2079, in calculate
weewx    | Aug 26 21:02:07 weewx[19] INFO user.rtgd: rtgdthread: ****     wgust = self.buffer['windGust'].history_max(ts, age=600).value
weewx    | Aug 26 21:02:07 weewx[19] INFO user.rtgd: rtgdthread: **** AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by gjr80** [comment]
Can you confirm what version of rtgd are you using? The code that caused the exception (line 2079) does not exist in the current release. You mentioned you manually installed the extension, is it possible you have installed an old version? Version 0.5.0 is the current release. You can confirm the version by checking the rtgd.py file at about line 20, and further down about line 626, you should find a couple of fairly obvious version strings, eg:

Version: 0.5.0                           Date: 7 February 2021

and

# version number of this script
RTGD_VERSION = '0.5.0'

**Comment by LMSSonos** [comment]
@gjr80 I can confirm to use version 0.5.0 - I'm using following steps in the docker file

```
RUN wget -O rtgd.tar.gz https://github.com/gjr80/weewx-realtime_gauge-data/releases/download/v0.5.0/rtgd-0.5.0.tar.gz
RUN ./bin/wee_extension --install=rtgd.tar.gz
```

I also saw that error lines do not match, I thought was the comments & python, but in the end I wasn't sure about that, not really python expert ;)

**Comment by LMSSonos** [comment]
Thank you, you were right, the link `https://github.com/gjr80/weewx-realtime_gauge-data/releases/download/v0.5.0/rtgd-0.5.0.tar.gz` I was using in the docker file did not point to the rtgd file, so I had another version running.

Thanks for pointing that out.
