### ISSUE TITLE
Rainrate error

### ISSUE THREAD

**Issue by Russell797** [gjr80/weewx-realtime_gauge-data#31]
Using 0.6.3 rainrate produces output some 25 times the correct value in inches. 

"rfall":"1.85","rrate":"18.00","rrateTM":"180.6",
when the rate was 0.71 in/hr
rainfall is correct
Rainrate gauge reads 18.00 in/hr

**Comment by gjr80** [comment]
Going to need a bit more information to track down the issue, the 25 factor suggests that somewhere a value in inches is being read as mm or vice versa. Can you please post some output:
1. A copy of `gauge-data.txt` generated by the extension, doesn't need to be showing erroneous rain data but needs to be complete.
2. A copy of a loop packet from your station, preferably close in time to the `gauge-data.txt` above. You can capture this from the console by [running WeeWX directly](http://weewx.com/docs/latest/usersguide.htm#Running_directly).
3. A copy of the `[RealtimeGaugeData]' stanza from `weewx.conf`. The information should be benign but just check and obfuscate any sensitive info like API keys etc.

**Comment by Russell797** [comment]
[RealtimeGaugeData]
    # This section is for the RTGD service.
    
    # Date format to be used in gauge-data.txt. Must be either %d/%m/%Y,
    # %m/%d/%Y or %Y/%m/%d. Separator may be forward slash '/' or a
    # hyphen '-'. Default is %Y/%m/%d.
    date_format = %Y/%m/%d
    
    # Time format to be used in gauge-data.txt. May be %H:%M or %h:%M.
    # Default is %H:%M
    time_format = %H:%M
    
    # Path to gauge-data.txt. Relative paths are relative to HTML_ROOT. If
    # empty HTML_ROOT is used, if setting omitted altogether /var/tmp is used.
    rtgd_path = /var/www/html/ss
    
    # Scrolling text display or 'forecast' field source. Case insensitive. 
    # All except Zambretti require a corresponding [[ ]] stanza. Uncomment and 
    # select one entry to enable.
    # scroller_source = text|file|WU|DS|Zambretti
    
    [[DS]]
    # Settings to be used for Darksky forecast block. Uncomment to use.
    
    # DarkSky API key
    # api_key = xxxxxxxxxxxxxxxx
    
    [[WU]]
    # Settings to be used for Weather Underground forecast block. Uncomment 
    # to use.
    
    # WU API key to be used when calling the WU API
    # api_key = xxxxxxxxxxxxxxxx        
    
    [[Text]]
    # Settings to be used for user specified text block. Uncomment to use.
    
    # user specified text to populate the 'forecast' field
     text = Near Realtime Gauges (Updated Every 4 Seconds)
    
    [[File]]
    # Settings to be used for first line of text file block. Uncomment to use.
    
    # Path and file name of file to use as block for the 'forecast' 
    # field. Must be a text file, first line only of file is read.
    # file = path/to/file/file_name
    
    [[StringFormats]]
        # formats for gauge-data.txt fields by unit type
        degree_C = %.1f
        degree_F = %.1f
        degree_compass = %.0f
        foot = %.0f
        hPa = %.1f
        inHg = %.2f
        inch = %.2f
        inch_per_hour = %.2f
        km_per_hour = %.1f
        km = %.1f
        mbar = %.1f
        meter = %.0f
        meter_per_second = %.1f
        mile = %.1f
        mile_per_hour = %.1f
        mm = %.1f
        mm_per_hour = %.1f
        percent = %.0f
        uv_index = %.1f
        watt_per_meter_squared = %.0f
    
    
    [[Groups]]
        # Units to be used in gauge-data.txt. Note not all available WeeWX units 
        # are supported for each group.         
        
        # Supported options for group_altitude are 'meter' or 'foot'
        group_altitude = foot
        # Supported options for group_pressure are 'inHg', 'mbar', or 'hPa'
        group_pressure = inHg
        # Supported options for group_rain are 'inch' or 'mm'
        group_rain = inch
        # Supported options for group_speed are 'mile_per_hour', 'km_per_hour' 
        # or 'meter_per_second'
        group_speed = mile_per_hour
        # Supported options for group_temperature are 'degree_F' or 'degree_C'
        group_temperature = degree_F

----------------------------------------------------------
{"BearingRangeFrom10":"5","BearingRangeTo10":"355","CurrentSolarMax":"0","LastRainTipISO":"2023/08/18 11:40","SensorContactLost":"0","SolarRad":"0","SolarRadTM":"0","TapptempTH":"14:50","TapptempTL":"21:41","TdewpointTH":"13:49","TdewpointTL":"21:40","TheatindexTH":"14:48","ThourlyrainTH":"00:00","ThumTH":"11:45","ThumTL":"21:32","TinhumTH":"14:49","TinhumTL":"00:00","TintempTH":"21:11","TintempTL":"06:31","TpressTH":"00:00","TpressTL":"16:16","TrrateTM":"15:39","TtempTH":"14:48","TtempTL":"01:19","TwchillTL":"01:19","TwgustTM":"15:43","UV":"0.0","UVTH":"0.0","WindRoseData":[20.0,20.0,7.0,4.0,1.0,5.0,15.0,15.0,8.0,1.0,1.0,0.0,3.0,2.0,15.0,18.0],"apptemp":"69.7","apptempTH":"89.8","apptempTL":"66.7","avgbearing":"328","bearing":"305","bearingTM":"121","build":"","cloudbaseunit":"ft","cloudbasevalue":"2670","date":"2023/08/18 21:41","dateFormat":"y/m/d","dew":"57.0","dewpointTH":"73.1","dewpointTL":"56.9","domwinddir":"NNE","forecast":"Near Realtime Gauges (Updated Every 4 Seconds)","heatindex":"67.7","heatindexTH":"85.7","hourlyrainTH":"0.0","hum":"68","humTH":"97","humTL":"68","humidex":"74.0","inhum":"53","inhumTH":"59","inhumTL":"53","intemp":"79.7","intempTH":"79.9","intempTL":"76.3","press":"29.73","pressH":"30.86","pressL":"28.67","pressTH":"29.88","pressTL":"29.59","presstrendval":"0.03","pressunit":"in","rainunit":"in","rfall":"1.86","rrate":"0.0","rrateTM":"180.6","temp":"68.0","tempTH":"81.4","tempTL":"66.6","temptrend":"-1.4","tempunit":"F","timeUTC":"2023,08,19,01,41,46","ver":"14","version":"4.10.2","wchill":"68.0","wchillTL":"66.6","wgust":"6.0","wgustTM":"10.0","windTM":"10.0","windrun":"20.1","windunit":"mph","wlatest":"1.0","wspeed":"1.3"}

--------------------------------------------------------------------------------
russell@weewx-server:~$ sudo sudo weewxd
LOOP:   2023-08-18 21:44:22 EDT (1692409462) 'altimeter': '29.732663980861023', 'appTemp': '70.2262559278246', 'barometer': '29.725', 'cloudbase': '2576.7781727028478', 'consBatteryVoltage': '4.45', 'dateTime': '1692409462', 'dayET': '0.0', 'dayRain': '1.86', 'dewpoint': '57.345376040107475', 'ET': 'None', 'extraAlarm1': '0', 'extraAlarm2': '0', 'extraAlarm3': '0', 'extraAlarm4': '0', 'extraAlarm5': '0', 'extraAlarm6': '0', 'extraAlarm7': '0', 'extraAlarm8': '0', 'forecastIcon': '2', 'forecastRule': '122', 'heatindex': '67.633', 'humidex': '74.04308351204932', 'inDewpoint': '61.55995637615756', 'inHumidity': '54.0', 'insideAlarm': '0', 'inTemp': '79.7', 'maxSolarRad': '0.0', 'monthET': '0.0', 'monthRain': '5.18', 'outHumidity': '69.0', 'outsideAlarm1': '0', 'outsideAlarm2': '0', 'outTemp': '67.9', 'pressure': '29.53902387389789', 'rain': 'None', 'rainAlarm': '0', 'rainRate': '0.0', 'soilLeafAlarm1': '0', 'soilLeafAlarm2': '0', 'soilLeafAlarm3': '0', 'soilLeafAlarm4': '0', 'stormRain': '1.86', 'stormStart': '1692331200', 'sunrise': '1692352560', 'sunset': '1692402180', 'txBatteryStatus': '0', 'usUnits': '1', 'windchill': '67.9', 'windDir': 'None', 'windGust': '0.0', 'windGustDir': 'None', 'windrun': 'None', 'windSpeed': '0.0', 'windSpeed10': '1.0', 'yearET': '0.0', 'yearRain': '34.99'

**Comment by gjr80** [comment]
Thank you. I believe I have found and fixed the issue. Could you please:

1. locate your existing `rtgd.py` (it may be in `/home/weewx/bin/user` or `/usr/share/weewx/user` depending on your WeeWX install type)
2. download the updated `rtgd.py` using:
```
wget -P /var/tmp https://raw.githubusercontent.com/gjr80/weewx-realtime_gauge-data/master/bin/user/rtgd.py
```
3. replace `rtgd.py` identified at 1. with the `rtgd.py` in `/var/tmp` downloaded at 2.
4. restart WeeWX

Unfortunately you will need to wait until some more rain falls before being able to see it the issue if fixed. Please let me know the outcome.

**Comment by Russell797** [comment]
Ok, it is raining and everything is working fine. Issue resolved.
