### ISSUE TITLE
After weewx restart max() arg is an empty sequence in fromBearing calculation

### ISSUE THREAD

**Issue by bakerkj** [gjr80/weewx-realtime_gauge-data#6]
Occasionally when I restart weewx I see this error:

Apr 27 22:00:15 HOSTNAME weewx[16906]: rtgdthread: **** Traceback (most recent call last):
Apr 27 22:00:15 HOSTNAME weewx[16906]: rtgdthread: ****   File "/usr/share/weewx/user/rtgd.py", line 926, in process_packet
Apr 27 22:00:15 HOSTNAME weewx[16906]: rtgdthread: ****     data = self.calculate(cached_packet)
Apr 27 22:00:15 HOSTNAME weewx[16906]: rtgdthread: ****   File "/usr/share/weewx/user/rtgd.py", line 1519, in calculate
Apr 27 22:00:15 HOSTNAME weewx[16906]: rtgdthread: ****     fromBearing = max((self.windDirAvg-d) if ((d-self.windDirAvg) < 0 < s) else None for x, y, s, d, t in self.buffer.wind_dir_list)
Apr 27 22:00:15 HOSTNAME weewx[16906]: rtgdthread: **** ValueError: max() arg is an empty sequence

**Comment by gjr80** [comment]
Fixed at commit https://github.com/gjr80/weewx-realtime_gauge-data/commit/e9f28795f7e370ec146bbe23b5ee36bad4b276ff (v0.2.13)

**Comment by bakerkj** [comment]
thanks
